{{- range $name, $lws := .Values.vllm }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-entrypoint-script
data:
  leader-entrypoint.sh: |+
    {{- $lws.leaderEntrypointScript | default $lws.entrypointScript | nindent 4 }}
    
  worker-entrypoint.sh: |+
    {{- $lws.workerEntrypointScript | default $lws.entrypointScript | nindent 4 }}
    
{{- end }}