{{- range $name, $deploy := .Values.deployments }}
{{- if ($deploy.service).ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  {{- if $deploy.service.ingressTransport }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ $name }}-middleware@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  ingressClassName: traefik
  {{- if $deploy.service.ingressTransport }}
  tls:
  - hosts:
    - {{ $name }}.app.home
  {{- end }}
  rules:
  - host: {{ $name }}.app.home
    http:
      paths:
      - backend:
          service:
            name: {{ $name }}
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
{{- if $deploy.service.ingressTransport }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $name }}-transport
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $name }}-middleware
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}
{{- end }}
